# Programming for Data Analysis: Investigation of numpy.random package

Author: Julian Dunne g00267940@gmit.ie

1 - create jupyter notebook explaining the use of the numpy.random package

2 - explain the use of the "Simple random data" and "Permutations" functions

3 - explain the use of at least 5 "Distributions" functions

4 - explain the use of seeds in generating pseudorandom numbers

Don't forget to include READ.ME file which only needs to include an explanation of what is contained in the repository and how to run the Jupyter Notebook  

# 1) The purpose of numpy.random
Numpy is a python package used for scientific and numerical computing. Numpy stores data in multidimensional arrays and is similiar to Python 'Lists' however it is more efficient at storing and accessing this data https://www.educba.com/introduction-to-numpy/?source=leftnav.

Numpy can access this information faster due to the data within these multidimensional arrays being fixed types i.e. float, integer or string. Numpy arrays does not contain different datatypes as can be used in Python 'Lists' which means Numpy does not check for datatypes when analysing data. This reduces the time required by Numpy to retrieve and analyse  data which is beneficial when analysing large amounts of data 
https://www.youtube.com/watch?v=GB9ByFAIAH4&t=1751s.


<img src="numpy_array.png">
<br>

<!--image from https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png -->

### Pseudo-random data:
The Numpy library has the ability to simulate random arrays of data, shuffle this data and to draw samples from this data based on specified distributions, all of which will be looked at further as part of this assignment. 

When introducing the Numpy random module it is interesting to note that the data generated using this method is not actually random. Computers work on programs which are a definitive set of instructions so an algorithm within the program must generate the random number as well. If there is a program to generate a random number it can be predicted. Meaning it is not a truly random number. Random numbers generated this way are called pseudo random. https://www.w3schools.com/python/numpy_random.asp


### Permuted Congruential Generator (PCG-64)
Numpy produces pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions http://www.numpy.org.cn/en/reference/routines/random.html#quick-start. 

BitGenerators do not directly provide random numbers and only contain methods used for seeding, getting or setting the state, jumping or advancing the state, and for accessing low-level wrappers for consumption by code that can efficiently access the functions provided https://numpy.org/devdocs/reference/random/bit_generators/index.html.
     
The Generator provides access to a wide range of distributions. The Generator relies on an the BitGenerator to manage state and generate the random bits, which are then transformed into random values from specific distributions. This structure allows alternative bit generators to be used with little code duplication. The default BitGenerator used by Generator is PCG64 https://numpy.org/devdocs/reference/random/generator.html.

PCG-64 is a 128-bit implementation of O’Neill’s permutation congruential generator. PCG-64 has a period of 2^{128} and supports advancing an arbitrary number of steps as well as 2^{127} streams https://numpy.org/devdocs/reference/random/bit_generators/pcg64.html. The Permuted Congruential Generator uses a linear congruential generator as the state-transition function. Linear congruential generators are known to be statistically weak, but PCG's state transition function only does half the work. PCG uses a technique called permutation functions on tuples to produce output that is much more random than the random number generators internal state. PCG's output functions are what gives it its excellent statistical performance and makes it hard predict from its output https://www.pcg-random.org/.

The numpy.random package serves many purposes, some of which will be looked at in greater detail in the following sections.
Some applications where random module is used include: 

1) Generate pseudo-random data which can be used to test machine learning models

2) Create different types of data using a range of distributions as part of statistical analysis on a data group

## Importing the required libraries

In [ ]:
#Import numpy and matplotlib libraries
import pandas as pd
import numpy as np
from numpy import random
import matplotlib.pyplot as plt

%matplotlib inline

# 2) Simple Random Data and Permutations Functions

Numpy has a number of functions for generating libraries of pseudo random data. Using built-in methods which will be discussed in the section below it can randomly create and configure this pseudo random data. These are numpy's Simple Random Data methods:

In [2]:
#Import the numpy library to begin
import numpy as np

## i) random.default_rng().integers() 
The random integers method replaces randomstate.randint method used in previous versions on numpy. Returns an array of random integers that are from the “discrete uniform” distribution for a specified dtype.
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers

In [3]:
# Generate a random array of 0 and 1 integers
rng_integers = np.random.default_rng().integers(2, size=(4))
rng_integers

array([1, 0, 0, 1], dtype=int64)

In [ ]:
# Code does not work - needs to be looked at again before submission
#Generate a signal using binary numbers using rng_integers generated above
sym_len = 8
rng_n = rng_integers

rng_n[np.where(rng_n == 1)] = 1
rng_n[np.where(rng_n == 0)] = 0

plt.stem(rng_n, use_line_collection=True)

#generate signal
sig = np.zeros(sym_len * rng_n)

id_n = np.where(rng_n == 1)

for i in id_n[0]:
    temp = int(i * sym_len)
    sig[temp:temp+sym_len] = 1
    

plt.plot(sig)

# https://www.youtube.com/watch?v=XCDvWF8XSC4

## ii) random.default_rng().random()
The random random method replaces randomstate.random_sample method used in previous versions on numpy. Returns an array of random floats from the “continuous uniform” distribution over the stated interval. 
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random

Random.random() can be used to create as many floating-point numbers in as many dimensions as is required. All values will be in the range 0.0 - 1.0 (low, high). Note that 1.0 is exclusive meaning all values are below 1.0.

In [4]:
rng_float = np.random.default_rng().random()
rng_float

0.11018090656130242

In [5]:
rng_multidim_array = np.random.default_rng().random((5,2))
rng_multidim_array

array([[0.26878353, 0.63830462],
       [0.01676694, 0.92881049],
       [0.43641589, 0.55624987],
       [0.84519323, 0.54539007],
       [0.6946869 , 0.28254847]])

## iii) random.default_rng().choice()
Generates a random sample from a given 1-D array which can be of a single data type such as either: integer, float or string. https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice

There are several applications for the random choice method:

1) Generate a random uniform sample with(out) replacement

2) Generate a random non-uniform sample using probability with(out) replacement

3) The above can be applied to an arbitrary array-like instead of just integers e.g. dtype=string

In [6]:
# Generate a random uniform sample without replacement
rng_choice_1 = np.random.default_rng().choice(10, 6, replace=False)
rng_choice_1

array([5, 0, 4, 7, 3, 9], dtype=int64)

In [7]:
# Generate a random non-uniform sample using probability 'p' with replacement
rng_choice_2 = np.random.default_rng().choice(5, 10, p=[0.2, 0, 0, 0.8, 0])
rng_choice_2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

## Human versus computer random choice guessing game

In this game a letter is chosen by the computer from a list and stored in the variable the_winning_letter.
You will will play against the computer to see who picks the correct letter first.
If you guess wrong and the computer guesses wrong then you will win by default!

<img src="lets_play.jpg">
<br>

<!--image from https://www.shutterstock.com/image-vector/lets-play-on-colorful-banner-1808027134 -->

In [8]:
#first import the library
import numpy as np

Using random choice method the computer picks the winning letter from the list and stores it in a variable.

In [9]:
list_of_letters = ['a', 'b', 'c',]
the_winning_letter= np.random.default_rng().choice(list_of_letters)

First guess is for you.

Note: Your guess will then removed from the list so it is not chosen again.

In [10]:
human_guess = 'b'
list_of_letters.remove(human_guess)

Program checks to see if you have guessed correctly. If you guess correctly first time then the kernel will restart and clear output as there is no reason to continue. If your guess is incorrect then continue the game. 

To restart and clear kernel output a web search found https://stackoverflow.com/questions/37472274/jupyter-disable-restart-kernel-warning/47055462#47055462.

In [11]:
if human_guess != the_winning_letter:
    print("Unlucky, not this time.")
else:
    print("That was quick")
    

Unlucky, not this time.


In [ ]:
#Only run this code block if you incorectly guessed the letter as it will restart the kernel and clear output
#allowing user to play the game again
#if the kernel is restarted you must import numpy library again to execute any code
from IPython.core.display import HTML
HTML("<script>Jupyter.notebook.kernel.restart()</script>")

The next guess is for the computer. Again the letter guessed is removed from the list.

In [12]:
comp_guess = np.random.default_rng().choice(list_of_letters)
list_of_letters.remove(comp_guess)

Program checks to see if the computer has guessed correctly.

In [13]:
if comp_guess == the_winning_letter:
    print("Computer wins!")
else:
    print("You have beaten the computer by default as this is the last letter left: ", list_of_letters)

Computer wins!



<img src="game_over.jpg">
<br>

<!--image from https://www.shutterstock.com/image-vector/decorative-game-over-text-fashion-poster-1307904490 -->

## iv) np.random.default_rng().bytes()
Returns string of length(length) based on specified number of random bytes(len).
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html#numpy.random.Generator.bytes

In [14]:
u=np.random.bytes(2)
u

b'^c'

In [15]:
#The type returned is shown as bytes
s = u
type(s)

bytes

## Permutation
Randomly permutes a sequence or to return a permuted range. Permute method allows user to pseudo-randomly change to element order in an array or to change the row order without changeing the element order for instances where an array contains more than one row. https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation.  

In [16]:
#change the order of the array - instead on return ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
rng_permute1 = np.random.default_rng().permutation(10)
rng_permute1

array([5, 3, 0, 4, 6, 1, 2, 8, 9, 7])

In [17]:
#change the order of the rows in the array without changing the order of the elements in each row
#Notice that for multivariate arrays only the row in each changes with itself e.g. [0,1,2] > [3,4,5]
arr_permute = np.arange(12).reshape((2, 2, 3))
rng_permute2 = np.random.default_rng().permutation(arr_permute)
rng_permute2

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  1,  2],
        [ 3,  4,  5]]])

## Shuffle
Returns a modified sequence by shuffling its contents pseudo-randomly. Method only shuffles the array along the first axis of a multi-dimensional array. The orders of sub arrays is changed but elements within each remain the same.

In [18]:
#Elements in each row are the same but are returned in a modified sequence
arr_sh1 = np.arange(9).reshape((3, 3))
rng_shuffle1 = np.random.default_rng().shuffle(arr_sh1, axis=1)
arr_sh1

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [19]:
#Method on shuffles the first axis of a multidimensional array. Elements in each row stay in the same sequence
arr_sh2 = np.arange(16).reshape((2, 2, 4))
rng_shuffle2 = np.random.default_rng().shuffle(arr_sh2, axis=1)
arr_sh2

array([[[ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[12, 13, 14, 15],
        [ 8,  9, 10, 11]]])

## Apply the permutation method to a pandas dataframe

In [20]:
#import the necessary libraries:
import numpy as np
import pandas as pd

In [21]:
#Create a pandas dataframe from the random_permutations.txt file (created by author just for example)
data = pd.read_csv('random_permutations.txt', delimiter=r",")
data.set_index(['Identifier', 'country', 'city', 'language'])
data

Identifier  country       city   language
0        Ire  Ireland     Dublin    english
1        Hun  Hungary   Budapest  hungarian
2        Ger  Germany     Berlin     german
3        Swe   Sweden  Stockholm    english
4        Fra   France      Paris     french

In [22]:
#pseudo-randomly change order of nrows using permute method
#generate a new row order called permuted_row
nrows = data.shape[0]
permuted_row = np.random.default_rng().permutation(nrows)

In [23]:
#New order of rows to be displayed in dataframe
permuted_row

array([0, 1, 2, 4, 3])

In [24]:
#Apply new order using the take function
data.take(permuted_row)

Identifier  country       city   language
0        Ire  Ireland     Dublin    english
1        Hun  Hungary   Budapest  hungarian
2        Ger  Germany     Berlin     german
4        Fra   France      Paris     french
3        Swe   Sweden  Stockholm    english

The code for the above dataframe permutation was written by the author with assistance from online searches including a video on Pandas DataFrames: Permutation https://www.youtube.com/watch?v=zr7O2egWKQc.